title:              MAT Lab Lab Log
email:              me@matkelly.com
description:        Writings and Reports from at MAT Lab Research Group at Drexel CCI
author:             Mat Kelly
baseurl:            "/"
url:                "https://log.lab.matkelly.com"

# Social Profiles
twitter_username:   machawk1
github_username:    machawk1
mastodon_username:  digipres.club/@machawk1
facebook_username: 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-target-blank
permalink: /:slug