name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    task_name: Spellgood
    steps:
    # The checkout step
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.28.0
      name: Spellcheck
      with:
        source_files: '**/*.md'
        task_name: Markdown